// Code generated by go-swagger; DO NOT EDIT.

package event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/keptn/keptn/mongodb-datastore/models"
)

// GetOpenEventsHandlerFunc turns a function with the right signature into a get open events handler
type GetOpenEventsHandlerFunc func(GetOpenEventsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOpenEventsHandlerFunc) Handle(params GetOpenEventsParams) middleware.Responder {
	return fn(params)
}

// GetOpenEventsHandler interface for that can handle valid get open events params
type GetOpenEventsHandler interface {
	Handle(GetOpenEventsParams) middleware.Responder
}

// NewGetOpenEvents creates a new http.Handler for the get open events operation
func NewGetOpenEvents(ctx *middleware.Context, handler GetOpenEventsHandler) *GetOpenEvents {
	return &GetOpenEvents{Context: ctx, Handler: handler}
}

/*GetOpenEvents swagger:route GET /event/open event getOpenEvents

Gets all open triggered events

*/
type GetOpenEvents struct {
	Context *middleware.Context
	Handler GetOpenEventsHandler
}

func (o *GetOpenEvents) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOpenEventsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetOpenEventsOKBody get open events o k body
// swagger:model GetOpenEventsOKBody
type GetOpenEventsOKBody struct {

	// events
	Events []*models.KeptnContextExtendedCE `json:"events"`

	// Pointer to the next page
	NextPageKey string `json:"nextPageKey,omitempty"`

	// Size of the returned page
	PageSize int64 `json:"pageSize,omitempty"`

	// Total number of events
	TotalCount int64 `json:"totalCount,omitempty"`
}

// Validate validates this get open events o k body
func (o *GetOpenEventsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEvents(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetOpenEventsOKBody) validateEvents(formats strfmt.Registry) error {

	if swag.IsZero(o.Events) { // not required
		return nil
	}

	for i := 0; i < len(o.Events); i++ {
		if swag.IsZero(o.Events[i]) { // not required
			continue
		}

		if o.Events[i] != nil {
			if err := o.Events[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getOpenEventsOK" + "." + "events" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetOpenEventsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetOpenEventsOKBody) UnmarshalBinary(b []byte) error {
	var res GetOpenEventsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
